new project
NastasiaIOSdev/TaskTwoV1 pull request #1
Opened 2021-06-28 09:20 UTC by NastasiaIOSdev

1. Create a new Xcode project
2. Create a new practice2 branch from master
3. Add the project to the version control system
4. Add the correct one .gitignore iOS Swift
5. Add lecturers to reviewers
6. Create a draft Pull-request.

2021-06-29 09:45 UTC, vasilevkin commented on TaskTwoV1/APIService/APICaller.swift
> +    struct Constants {
move to the separate file

2021-06-29 09:48 UTC, vasilevkin requested changes

2021-06-29 09:48 UTC, vasilevkin commented on TaskTwoV1/APIService/APICaller.swift
> +// MARK: - Model
move to the separate file

2021-06-29 09:48 UTC, vasilevkin commented on TaskTwoV1/Controller/ViewController.swift
> +//                    BigTableViewCellViewModel(
do not include commented out code in pr

2021-06-29 09:48 UTC, vasilevkin commented on TaskTwoV1/Controller/ViewController.swift
> +       return 17
do not use magic numbers, count it dynamically

2021-06-29 21:03 UTC, NastasiaIOSdev commented on TaskTwoV1/Controller/ViewController.swift
> +//                    BigTableViewCellViewModel(
ок

2021-06-29 21:04 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/APICaller.swift
> +// MARK: - Model
already fixed

2021-06-29 21:09 UTC, NastasiaIOSdev commented on TaskTwoV1/Controller/ViewController.swift
> +       return 17
I corrected this remark in the third practice because I built a working model there, in the second task I will finish working with the network and configure the model and fix this return

2021-06-30 12:21 UTC, vasilevkin requested changes
separate files in different pr for Practice 2 and 3
and don't commit commented out code.

Table should contain all items in animal list

2021-07-01 10:50 UTC, vasilevkin commented
it looks much better now.
Proceed with additional task or next practice.

2021-07-29 09:14 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/APICaller.swift
> +    struct Constants {
fix

2021-07-29 09:43 UTC, NastasiaIOSdev commented
Fixed all comments

2021-07-29 13:05 UTC, vasilevkin approved these changes

2021-07-29 15:41 UTC, merged