Practice3
NastasiaIOSdev/TaskTwoV1 pull request #2
Opened 2021-06-30 22:50 UTC by NastasiaIOSdev

2021-07-01 10:53 UTC, vasilevkin commented on TaskTwoV1/Cats/CustomCells/HalfWidthTableViewCell.swift
> +                guard let data = data, error == nil else {
better use  let error = error and guard let
try do not use nil comparison in direct way ( == nil )

2021-07-01 10:54 UTC, vasilevkin requested changes
it looks better, proceed with additional tasks or next practice
you are on the correct way!

2021-07-01 20:13 UTC, NastasiaIOSdev commented
Thank you for the good words, Sergey)))!!

2021-07-29 09:18 UTC, NastasiaIOSdev commented on TaskTwoV1/Cats/CustomCells/HalfWidthTableViewCell.swift
> +                guard let data = data, error == nil else {
fix

2021-07-29 09:43 UTC, NastasiaIOSdev commented
Fixed all comments

2021-08-03 06:52 UTC, vasilevkin approved these changes

2021-08-03 07:17 UTC, merged