Practice4
NastasiaIOSdev/TaskTwoV1 pull request #3
Opened 2021-07-04 23:08 UTC by NastasiaIOSdev

2021-07-06 14:09 UTC, alekseykorol commented on TaskTwoV1/APIService/CellModel.swift
> +    var imageData: Data? = nil
Initializing an optional variable with nil is redundant ([Redundant Optional Initialization](https://realm.github.io/SwiftLint/redundant_optional_initialization.html))

Please check project with [SwiftLint](https://github.com/realm/SwiftLint) and fix warnings.
("swiftlint autocorrect" can also be used)

2021-07-06 14:22 UTC, alekseykorol commented on TaskTwoV1/CatToDog/Controller/MainViewController.swift
> +    @IBOutlet var tableViewSecond: UITableView!
IBOutlets should be private to avoid leaking UIKit to higher layers ([Private Outlet](https://realm.github.io/SwiftLint/private_outlet.html))

2021-07-06 14:35 UTC, alekseykorol commented on TaskTwoV1/Cats/CustomCells/FullWidthTableViewCell.swift
> +extension UIView {
Please move extension in a separate file

2021-07-06 14:39 UTC, alekseykorol commented on TaskTwoV1/CatToDog/CustomCells&/FirstTableViewCell.swift
> +        let cell = collectionViewSecond.dequeueReusableCell(withReuseIdentifier: CollectionViewCell.identifaer, for: indexPath) as! CollectionViewCell
Force casts should be avoided ([Force Cast](https://realm.github.io/SwiftLint/force_cast.html)).

2021-07-07 17:45 UTC, NastasiaIOSdev commented on TaskTwoV1/CatToDog/Controller/MainViewController.swift
> +    @IBOutlet var tableViewSecond: UITableView!
fixed on:   @IBOutlet weak var tableViewSecond: UITableView!

2021-07-07 17:51 UTC, NastasiaIOSdev commented on TaskTwoV1/CatToDog/CustomCells&/SecondTableViewCell.swift
> +        func layoutSubviews() {
a stupid mistake due to inattention. fixed it.

2021-07-07 18:23 UTC, NastasiaIOSdev commented on TaskTwoV1/CatToDog/CustomCells&/FirstTableViewCell.swift
> +        let cell = collectionViewSecond.dequeueReusableCell(withReuseIdentifier: CollectionViewCell.identifaer, for: indexPath) as! CollectionViewCell
fixed it:  guard let cell = collectionViewSecond.dequeueReusableCell(withReuseIdentifier: CollectionViewCell.identifaer, for: indexPath) as? CollectionViewCell else { fatalError()
        }

2021-07-07 19:22 UTC, NastasiaIOSdev commented on TaskTwoV1/CatToDog/CustomCells&/FirstTableViewCell.swift
> +        let cell = collectionViewSecond.dequeueReusableCell(withReuseIdentifier: CollectionViewCell.identifaer, for: indexPath) as! CollectionViewCell
![Снимок экрана 2021-07-08 в 00 14 40](https://user-images.githubusercontent.com/48592495/124816428-f5a5ef80-df81-11eb-91db-95ca0e78480c.png).  SwiftLint installed. A lot of things!!! I need to fix all this somehow.

2021-07-07 19:23 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/CellModel.swift
> +    var imageData: Data? = nil
SwiftLint installed. A lot of things!!! I need to fix all this somehow.   
![Снимок экрана 2021-07-08 в 00 14 40](https://user-images.githubusercontent.com/48592495/124817041-b035f200-df82-11eb-962c-dc1e84f4a586.png)

2021-07-08 06:46 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/CellModel.swift
> +    var imageData: Data? = nil
I checked the project using SwiftLint and fixed the warnings.
I also used the " swiftlint autocorrect".
Now:  
![Снимок экрана 2021-07-08 в 11 42 20](https://user-images.githubusercontent.com/48592495/124875205-0e45f200-dfe2-11eb-89cc-f0d3e3e7ae14.png)

2021-07-13 14:58 UTC, alekseykorol commented on TaskTwoV1/CatToDog/Controller/MainViewController.swift
> +    @IBOutlet var tableViewSecond: UITableView!
Please fix all IBOutlets.

2021-07-14 17:59 UTC, NastasiaIOSdev commented on TaskTwoV1/CatToDog/Controller/MainViewController.swift
> +    @IBOutlet var tableViewSecond: UITableView!
Done :)

2021-07-26 09:23 UTC, vasilevkin commented
error: /Users/svasilev/dev/paw/gif.gif: No such file or directory (in target 'TaskTwoV1' from project 'TaskTwoV1')

Project should compile after every commit.

2021-07-26 09:24 UTC, vasilevkin commented
Please add SwiftLint to the project and fix all errors/warnings.

2021-07-26 14:38 UTC, NastasiaIOSdev commented
> error: /Users/svasilev/dev/paw/gif.gif: No such file or directory (in target 'TaskTwoV1' from project 'TaskTwoV1')
> 
> Project should compile after every commit.

Good afternoon, Sergey. I have updated the project, I hope the gif has been used in the project and will work. Perhaps this is some kind of bug. Let me know if it is not fixed and the gif does not appear in the project. Everything works locally for me.

2021-07-26 14:51 UTC, NastasiaIOSdev commented
> Please add SwiftLint to the project and fix all errors/warnings.

swiftLint reinstalls, all errors fixed, warning except for three things - fixed

2021-08-04 11:20 UTC, vasilevkin requested changes
do not include Pods in pr
check/update gitignore

2021-08-04 20:11 UTC, NastasiaIOSdev commented on .swiftlint.yml
> -  13
fixed

2021-08-04 20:11 UTC, NastasiaIOSdev commented on TaskTwoV1/App/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "Person")
fixed

2021-08-04 20:12 UTC, NastasiaIOSdev commented on .swiftlint.yml
> +  12
fixed. and remembered

2021-08-05 14:12 UTC, NastasiaIOSdev commented
> do not include Pods in pr
> check/update gitignore

Done. added line 

# Cocoapods
Pods/

2021-08-05 14:13 UTC, NastasiaIOSdev commented
> error: /Users/svasilev/dev/paw/gif.gif: No such file or directory (in target 'TaskTwoV1' from project 'TaskTwoV1')
> 
> Project should compile after every commit.

fixed

2021-08-05 15:41 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-06 08:12 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-06 10:27 UTC, vasilevkin requested changes
Double check and remove all pod files from this pr.
It should contain your changes only.

2021-08-06 14:52 UTC, NastasiaIOSdev commented
> Double check and remove all pod files from this pr.
> It should contain your changes only.

2021-08-07 15:01 UTC, NastasiaIOSdev commented on TaskTwoV1/App/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "Person")
check please

2021-08-07 15:01 UTC, NastasiaIOSdev commented
> Double check and remove all pod files from this pr.
> It should contain your changes only.
> 
> remove all pod files. it is fixed problem?
> reinstalled cocoapods and swiftlint

done

2021-08-07 15:03 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-10 05:37 UTC, NastasiaIOSdev commented
> Double check and remove all pod files from this pr.
> It should contain your changes only.
> 
> remove all pod files. it is fixed problem?
> reinstalled cocoapods and swiftlint

Sergey, please check all requests are fixed in this pr. Thanks for the help.

2021-08-10 09:33 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-14 09:32 UTC, merged