practice-5
NastasiaIOSdev/TaskTwoV1 pull request #4
Opened 2021-07-26 18:32 UTC by NastasiaIOSdev

2021-07-28 08:10 UTC, vasilevkin commented
this pr should contain changes related to practice 5 only.
Please do not include your changes from previous practices to this pr.

2021-07-28 11:14 UTC, NastasiaIOSdev commented
> this pr should contain changes related to practice 5 only.
> Please do not include your changes from previous practices to this pr.

ok, the task is clear and accepted for work

2021-07-30 09:41 UTC, NastasiaIOSdev commented
> > this pr should contain changes related to practice 5 only.
> > Please do not include your changes from previous practices to this pr.
> 
> ok, the task is clear and accepted for work

Can I work with the practice3 requirements from the practice4 branch in my current situation? Thank you for your time, Sergey.

2021-08-03 06:58 UTC, vasilevkin requested changes
good start, continue

2021-08-03 06:58 UTC, vasilevkin commented on .swiftlint.yml
> +- 500 # warning
this is a really bad practice.
Please do not tweak swiftlint config, but return default settings and fix all warnings and errors.

2021-08-03 06:58 UTC, vasilevkin commented on TaskTwoV1/Protocols&Extensions/AllBreedExtensions/TestViewController+Extensions.swift
> +            for (index, image) in self.breeds!.message.enumerated() where index == indexPath.row {
use some data structure or model instead of (index, image)

2021-08-03 06:58 UTC, vasilevkin commented on TaskTwoV1/Protocols&Extensions/AllBreedExtensions/TestViewController+Extensions.swift
> +            for (index, image) in self.breeds!.message.enumerated() where index == indexPath.row {
do not force unwrap optionals

2021-08-03 06:58 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +//        if mainMap.annotations.count > 1 {
do not commit commented out code in the final pr, 
for now in draft WIP pr it's ok

2021-08-03 07:35 UTC, NastasiaIOSdev commented on .swiftlint.yml
> +- 500 # warning
Fixed

2021-08-03 07:43 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +//        if mainMap.annotations.count > 1 {
iI took it to work

2021-08-04 20:29 UTC, NastasiaIOSdev commented on TaskTwoV1/Protocols&Extensions/AllBreedExtensions/TestViewController+Extensions.swift
> +            for (index, image) in self.breeds!.message.enumerated() where index == indexPath.row {
fixed

2021-08-04 20:29 UTC, NastasiaIOSdev commented on TaskTwoV1/Protocols&Extensions/AllBreedExtensions/TestViewController+Extensions.swift
> +            for (index, image) in self.breeds!.message.enumerated() where index == indexPath.row {
fixed

2021-08-05 15:44 UTC, NastasiaIOSdev commented
> this pr should contain changes related to practice 5 only.
> Please do not include your changes from previous practices to this pr.

done

2021-08-05 16:09 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +//        if mainMap.annotations.count > 1 {
fix

2021-08-05 16:27 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-06 10:23 UTC, vasilevkin commented
> > this pr should contain changes related to practice 5 only.
> > Please do not include your changes from previous practices to this pr.
> 
> done

You wrote 'done', but this comment is not fixed.
Please double check what files are included in this pr.

2021-08-16 12:01 UTC, closed without merging