practice5 setup
NastasiaIOSdev/TaskTwoV1 pull request #5
Opened 2021-08-16 12:39 UTC by NastasiaIOSdev

2021-08-19 09:17 UTC, vasilevkin requested changes

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/APIService/WeatherManager.swift
> +    let weatherURL = "https://api.openweathermap.org/data/2.5/onecall?appid=ff554f01a90bb15acaa4b59c8e15462e&units=metric"
better to move api key into separate constant.

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/APIService/WeatherManager.swift
> +        let urlString = "\(weatherURL)&lat=\(latitude)&lon=\(longitude)&lang=\(Locale.current.languageCode!)&exclude=minutely,hourly,alerts"
do not use force unwrap optionals.

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/APIService/WeatherManager.swift
> +                if error != nil {
better do not use nil comparison,
use 
if let error = error 
or something similar

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/Info.plist
> +	<string>Do you ....</string>
add some useful description

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +            annotationView?.calloutOffset = CGPoint(x: -4, y: 4)
do not use magic numbers

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
using Any is not a good practice

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                let spam = MKCoordinateSpan(latitudeDelta: 0.05, longitudeDelta: 0.05)
do not use magic numbers

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +            if error == nil {
do not use nil comparison , use more swift style solution
if let, guard ...

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                annotation.coordinate = (placemark?.location?.coordinate)!
do not use force unwrap optionals

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                print("Error")
better to print some dynamic error description.
it helps to understand what error is and how to debug it.

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/SettingsViewController.swift
> +class SettingsViewController: UIViewController {
why this file exist?
is it do anything useful?

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +            wetherPicture.image = image?.withAlignmentRectInsets(UIEdgeInsets(top: -5, left: -5, bottom: -5, right: -5))
do not use magic numbers

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
avoid Any if possible

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/WeekForecastViewController.swift
> +        weatherView.layer.cornerRadius = 20
avoid magic numbers

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/WeatherCells/WeekForecastCell.swift
> +            if #available(iOS 14, *) {
why check system version if code is the same ?

2021-08-19 09:17 UTC, vasilevkin commented on TaskTwoV1/View/WeatherCells/WeekForecastCell.swift
> +            weatherPicture.image = image?.withAlignmentRectInsets(UIEdgeInsets(top: -5, left: -5, bottom: -5, right: -5))
avoid magic numbers

2021-08-19 09:18 UTC, vasilevkin requested changes
it's much better now, but fix comments

2021-08-19 13:11 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/WeatherManager.swift
> +    let weatherURL = "https://api.openweathermap.org/data/2.5/onecall?appid=ff554f01a90bb15acaa4b59c8e15462e&units=metric"
fixed

2021-08-19 14:26 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
What should I use instead in this case?

2021-08-19 14:37 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/SettingsViewController.swift
> +class SettingsViewController: UIViewController {
Still in work

2021-08-19 18:46 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/WeatherManager.swift
> +        let urlString = "\(weatherURL)&lat=\(latitude)&lon=\(longitude)&lang=\(Locale.current.languageCode!)&exclude=minutely,hourly,alerts"
fixed

2021-08-19 18:48 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +            annotationView?.calloutOffset = CGPoint(x: -4, y: 4)
fixed

2021-08-19 18:50 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                let spam = MKCoordinateSpan(latitudeDelta: 0.05, longitudeDelta: 0.05)
fixed

2021-08-19 18:51 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +            if error == nil {
fixed

2021-08-19 18:57 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                annotation.coordinate = (placemark?.location?.coordinate)!
fixed

2021-08-19 18:58 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +            wetherPicture.image = image?.withAlignmentRectInsets(UIEdgeInsets(top: -5, left: -5, bottom: -5, right: -5))
fixed

2021-08-19 19:00 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/WeekForecastViewController.swift
> +        weatherView.layer.cornerRadius = 20
fixed

2021-08-19 19:02 UTC, NastasiaIOSdev commented on TaskTwoV1/View/WeatherCells/WeekForecastCell.swift
> +            if #available(iOS 14, *) {
fixed

2021-08-19 19:03 UTC, NastasiaIOSdev commented on TaskTwoV1/View/WeatherCells/WeekForecastCell.swift
> +            weatherPicture.image = image?.withAlignmentRectInsets(UIEdgeInsets(top: -5, left: -5, bottom: -5, right: -5))
fixed

2021-08-19 19:05 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                print("Error")
fixed

2021-08-19 19:06 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/WeatherManager.swift
> +                if error != nil {
fixed

2021-08-19 19:21 UTC, NastasiaIOSdev commented on TaskTwoV1/Info.plist
> +	<string>Do you ....</string>
fixed

2021-08-20 05:01 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
in the process of fixing

2021-08-20 08:59 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
this comment is not mandatory,
just try to understand type system and use best practices.

2021-08-20 09:00 UTC, vasilevkin commented
it's much better now,
continue to implement the task, you're on the correct way!

2021-08-21 08:46 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/WeatherDetailViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
avoid Any, fixed

2021-08-21 15:58 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
fixed

2021-08-21 16:04 UTC, NastasiaIOSdev commented
fixed all comments

2021-08-31 12:15 UTC, NastasiaIOSdev commented
Can I merge this branch into the master branch?

2021-09-05 06:06 UTC, NastasiaIOSdev commented
fixed all comments

2021-09-06 11:17 UTC, vasilevkin requested changes

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/APIService/Model/WeatherModel/WeatherData2.swift
> +struct WeatherData2: Codable {
use more significant names

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/APIService/WeatherManager.swift
> +        let urlString = "\(url)&appid=\(apikey)&\(units)&lat=\(latitude)&lon=\(longitude)&lang=\(Locale.current.languageCode ?? "en")&exclude=minutely,hourly,alerts"
may be it can me more readable, there are parameters in queries 
try to make requests without using & explicitly

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/APIService/WeatherManager.swift
> +                    let newDay = DailyModel(dailyDt: day.dtDaily ?? 0,
try to avoid magic numbers

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/Constants/Constants.swift
> +    let weatherURL =  "https://api.openweathermap.org/data/2.5/onecall?&"
try to use more distinguishable names

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/Core Data/Helpers/PinInfo.swift
> +    func mapItem() -> MKMapItem {
add empty string

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/Core Data/Helpers/PinInfo.swift
> +    var sub: String {
add empty string

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/Core Data/Helpers/PinInfo.swift
> +    let desc: String
better use long understandable variable names, clarity over brevity

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/Protocols&Extensions/WeatherExtensions/MapViewController+Extensions.swift
> +        cell.textLabel?.attributedText = hightLightedText(searchResult.title, inRanges: searchResult.titleHighlightRanges, size: 17.0)
try to avoid magic numbers

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +    @IBOutlet weak var mainMap: MKMapView!
move @IBOutlet section on top of var section
do not mix variables and constant declarations with function implementations
try to make code more structured and readable

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                            latitude: 55.165273,
move magic numbers to some constants

2021-09-06 11:17 UTC, vasilevkin commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                          description: "Place",
check alignment

2021-09-18 12:00 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/Model/WeatherModel/WeatherData2.swift
> +struct WeatherData2: Codable {
fixed

2021-09-18 12:00 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/WeatherManager.swift
> +        let urlString = "\(url)&appid=\(apikey)&\(units)&lat=\(latitude)&lon=\(longitude)&lang=\(Locale.current.languageCode ?? "en")&exclude=minutely,hourly,alerts"
fixed

2021-09-18 12:00 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/WeatherManager.swift
> +                    let newDay = DailyModel(dailyDt: day.dtDaily ?? 0,
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/Constants/Constants.swift
> +    let weatherURL =  "https://api.openweathermap.org/data/2.5/onecall?&"
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/Core Data/Helpers/PinInfo.swift
> +    var sub: String {
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/Core Data/Helpers/PinInfo.swift
> +    let desc: String
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/Protocols&Extensions/WeatherExtensions/MapViewController+Extensions.swift
> +        cell.textLabel?.attributedText = hightLightedText(searchResult.title, inRanges: searchResult.titleHighlightRanges, size: 17.0)
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +    @IBOutlet weak var mainMap: MKMapView!
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                            latitude: 55.165273,
fixed

2021-09-18 12:01 UTC, NastasiaIOSdev commented on TaskTwoV1/View/Controllers/Weather/MapViewController.swift
> +                          description: "Place",
fixed

2021-09-18 12:03 UTC, NastasiaIOSdev commented
fixed all comments

2021-09-20 06:55 UTC, vasilevkin approved these changes
LGTM

2021-09-20 06:58 UTC, NastasiaIOSdev commented
it is possible to make a merge in the main?

2021-09-20 14:11 UTC, merged