practice6 setup
NastasiaIOSdev/TaskTwoV1 pull request #6
Opened 2021-08-18 12:42 UTC by NastasiaIOSdev

2021-08-19 09:05 UTC, vasilevkin requested changes
Good start for Practice 6 , way to go!

2021-08-19 09:05 UTC, vasilevkin commented on TaskTwoV1/Constants/Constants.swift
> +    static let topHeadlinesURL = URL(string: "https://newsapi.org/v2/top-headlines?country=us&apiKey=bd85a9f5eb6c44aa95856a39ed4eeeea")
better to move api key into separate let constant and use string concatenation.

2021-08-19 09:05 UTC, vasilevkin commented on TaskTwoV1/Protocols&Extensions/NewsExtensions/NewsViewController+Extensions.swift
> +        return CGSize(width: collectionView.frame.width / (self.listType == 2 ? 2 : 1) - 10, height: collectionView.frame.height/4 - 15)
do not use magic numbers

2021-08-19 12:27 UTC, NastasiaIOSdev commented on TaskTwoV1/Constants/Constants.swift
> +    static let topHeadlinesURL = URL(string: "https://newsapi.org/v2/top-headlines?country=us&apiKey=bd85a9f5eb6c44aa95856a39ed4eeeea")
fixed

2021-08-31 08:25 UTC, vasilevkin approved these changes

2021-08-31 08:25 UTC, vasilevkin commented on TaskTwoV1/APIService/Model/NewsModel/NewsDataModel.swift
> +                self.totalArticlesCount = response.totalResults < 100 ? response.totalResults : 100
better move 100 to some constant

2021-08-31 08:34 UTC, NastasiaIOSdev commented on TaskTwoV1/APIService/Model/NewsModel/NewsDataModel.swift
> +                self.totalArticlesCount = response.totalResults < 100 ? response.totalResults : 100
fixed

2021-08-31 09:12 UTC, merged